# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Test build Palladian

on:
  # Runs on pushes targeting the default branch
  ["pull_request"]

concurrency:
  group: "test"
  cancel-in-progress: false

jobs:
  # WIP でジョブがスキップされてもCIが失敗した扱いにならないようにするため
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip job"

  # WIP がコミットメッセージに含まれているとジョブを起動しない
  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, 'WIP')"
    steps:
      - run: echo "no WIP"

  build-test-v1:
    runs-on: ubuntu-latest
    needs: before
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: docker compose -f compose.test.yaml run app-ubuntu-v1 nimble build

  build-test-v2:
    runs-on: ubuntu-latest
    needs: before
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: docker compose -f compose.test.yaml run app-ubuntu-v2 nimble build
